In [ ]:
# series is 1-d
# dataframes is 2-d

In [11]:
import pandas as pd
import numpy as np

In [3]:
## series
## panda series is 1d array like object, similar to a column in table

data = [1,2,3,4,5,6]
series=pd.Series(data)
print("series \n", series)

# left coulmn of o/p is the default indices
print(type(series))

series
 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.Series'>

In [ ]:
# create a series from dictinoary elements
data = {'a': 1, 'b': 2, 'c': 3, 'aatmaram': 5}
series_dict = pd.Series(data)
print(series_dict) # default index has changed, ' keys will become the index
# pandas uses the order how the elements are inserted in dictionary

a           1
bbbb        2
c           3
aatmaram    5
dtype: int64

In [8]:
# giving specific index order
data = [1,2,3]
index = ['z', 'm', 'o']
pd.Series(data, index=index)

z    1
m    2
o    3
dtype: int64

In [9]:
# dataframe - it is 2dimensional, which can contain heterogenuous data

# create a dataframe from a dictionary of list
data = {
    'Name': ['Ramesh', 'Suresh', 'Mahesh'],
    'Age': [20, 52, 26],
    'City': ['Pune', 'Gurgaon', 'Assam']
}


df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age     City
0  Ramesh   20     Pune
1  Suresh   52  Gurgaon
2  Mahesh   26    Assam
<class 'pandas.DataFrame'>

In [12]:
np.array(df)

array([['Ramesh', 20, 'Pune'],
       ['Suresh', 52, 'Gurgaon'],
       ['Mahesh', 26, 'Assam']], dtype=object)

In [15]:
# create a dataframe from list of dictionaries
data = [
    {'Name': 'Ramesh', 'Age': 20, 'City': 'Pune'},
    {'Name': 'Suresh', 'Age': 52, 'City': 'Gurgaon'},
    {'Panda': 'Mahesh', 'Age': 26, 'City': 'Assam'}
]

df = pd.DataFrame(data)
print(df)

     Name  Age     City   Panda
0  Ramesh   20     Pune     NaN
1  Suresh   52  Gurgaon     NaN
2     NaN   26    Assam  Mahesh

In [19]:
df = pd.read_csv('sales_data.csv')
df.head(5)
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
25,TXN1026,2026-01-27,Sports,Dumbbell Set,2,3500,7000,South,UPI
26,TXN1027,2026-01-28,Electronics,Noise Cancelling Headphones,2,8500,17000,East,Credit Card
27,TXN1028,2026-01-29,Clothing,Sneakers,3,3200,9600,West,Debit Card
28,TXN1029,2026-01-30,Grocery,Green Tea Pack,7,280,1960,North,UPI
29,TXN1030,2026-01-31,Electronics,External SSD 1TB,2,6500,13000,South,Net Banking

In [22]:
# accessing data fromd dataframe


# create a dataframe from list of dictionaries
data = [
    {'Name': 'Ramesh', 'Age': 20, 'City': 'Pune'},
    {'Name': 'Suresh', 'Age': 52, 'City': 'Gurgaon'},
    {'Name': 'Mahesh', 'Age': 26, 'City': 'Assam'}
]

df = pd.DataFrame(data)
df

     Name  Age     City
0  Ramesh   20     Pune
1  Suresh   52  Gurgaon
2  Mahesh   26    Assam

In [23]:
df['Name']

0    Ramesh
1    Suresh
2    Mahesh
Name: Name, dtype: str

In [24]:
type(df['Name'])

pandas.Series

In [25]:
df.loc[0] # 0th row

Name    Ramesh
Age         20
City      Pune
Name: 0, dtype: object

In [26]:
# df.iloc[row_position, column_position]
df.iloc[0]

Name    Ramesh
Age         20
City      Pune
Name: 0, dtype: object

In [28]:
df.iloc[0, 1]

np.int64(20)

In [ ]:
# accessing a specified element
df.at[1, 'Age'] # from age takes 1st index

np.int64(52)

In [32]:
# accesing a specified element using iat
df.iat[2,2]

'Assam'

In [33]:
df

     Name  Age     City
0  Ramesh   20     Pune
1  Suresh   52  Gurgaon
2  Mahesh   26    Assam

In [ ]:
# data manupilation with dataframe
# adding a col
df['salary'] = [100, 200, 130]
df

     Name  Age     City  salary
0  Ramesh   20     Pune     100
1  Suresh   52  Gurgaon     200
2  Mahesh   26    Assam     130

In [37]:
# removing a col
# without inplce this is not a permanenet operation
df.drop('salary', axis=1, inplace=True) # by default it check in row index

In [36]:
df

     Name  Age     City  salary
0  Ramesh   20     Pune     100
1  Suresh   52  Gurgaon     200
2  Mahesh   26    Assam     130

In [38]:
df

     Name  Age     City
0  Ramesh   20     Pune
1  Suresh   52  Gurgaon
2  Mahesh   26    Assam

In [42]:
## add in age column
df['Age'] = df['Age']+1

In [43]:
df

     Name  Age     City
0  Ramesh   21     Pune
1  Suresh   53  Gurgaon
2  Mahesh   27    Assam

In [44]:
df.drop(0) # drop based on row

     Name  Age     City
1  Suresh   53  Gurgaon
2  Mahesh   27    Assam

In [45]:
df

     Name  Age     City
0  Ramesh   21     Pune
1  Suresh   53  Gurgaon
2  Mahesh   27    Assam

In [46]:
df.drop(0, inplace=True)

In [47]:
df

     Name  Age     City
1  Suresh   53  Gurgaon
2  Mahesh   27    Assam

In [48]:
df = pd.read_csv('sales_data.csv')

In [49]:
df.describe()

       Units Sold  Unit Price  Total Revenue
count   30.000000    30.00000      30.000000
mean     4.133333  2660.00000    6917.000000
std      2.255007  2637.34323    4005.158011
min      1.000000   250.00000    1900.000000
25%      2.000000   787.50000    3787.500000
50%      3.500000  1650.00000    6450.000000
75%      5.750000  3425.00000    9375.000000
max     10.000000  9500.00000   17000.000000