In [2]:
import pandas as pd

In [10]:
df = pd.read_csv('data.csv')

# fetch first 5 rows
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [11]:
# last 5 rows
df.tail(5)

          Date Category  Value   Product  Sales Region
95  2023-04-06        B   51.0  Product3    NaN  North
96  2023-04-07        C   24.0  Product1  339.0   East
97  2023-04-08        A   65.0  Product2  777.0  South
98  2023-04-09        B   47.0  Product3  588.0   West
99  2023-04-10        C   80.0  Product1  905.0  North

In [12]:
df.describe()

           Value       Sales
count  96.000000   96.000000
mean   50.510417  609.447917
std    25.664637  240.200393
min     7.000000  108.000000
25%    27.750000  420.500000
50%    48.500000  613.500000
75%    71.250000  824.000000
max    99.000000  999.000000

In [13]:
df.dtypes

Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object

In [14]:
# handling missing values
df.isnull() # true means their is a missing value

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
..    ...       ...    ...      ...    ...     ...
95  False     False  False    False   True   False
96  False     False  False    False  False   False
97  False     False  False    False  False   False
98  False     False  False    False  False   False
99  False     False  False    False  False   False

[100 rows x 6 columns]

In [15]:
df.isnull().any(axis=1) # checs any true in each row

0     False
1     False
2     False
3     False
4     False
      ...
95     True
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [16]:
df.isnull().sum()

Date        0
Category    0
Value       4
Product     3
Sales       4
Region      2
dtype: int64

In [18]:
# filling missing values with 0
df_filled = df.fillna(0)

In [20]:
# filling missing values with the mean of th column
df['Sales_fillNA'] = df['Sales'].fillna(df['Sales'].mean())
df

          Date Category  Value   Product  Sales Region  Sales_fillNA
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000
..         ...      ...    ...       ...    ...    ...           ...
95  2023-04-06        B   51.0  Product3    NaN  North    609.447917
96  2023-04-07        C   24.0  Product1  339.0   East    339.000000
97  2023-04-08        A   65.0  Product2  777.0  South    777.000000
98  2023-04-09        B   47.0  Product3  588.0   West    588.000000
99  2023-04-10        C   80.0  Product1  905.0  North    905.000000

[100 rows x 7 columns]

In [21]:
df.dtypes

Date                str
Category            str
Value           float64
Product             str
Sales           float64
Region              str
Sales_fillNA    float64
dtype: object

In [24]:
# renaming columns
df = df.rename(columns={'Date':'Sale Date'})
df.head()

    Sale Date Category  Value   Product  Sales Region  Sales_fillNA
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [27]:
# change datatypes
df['Value_new'] = df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

    Sale Date Category  Value   Product  Sales Region  Sales_fillNA  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         754.0         28
1  2023-01-02        B   39.0  Product3  110.0  North         110.0         39
2  2023-01-03        C   32.0  Product2  398.0   East         398.0         32
3  2023-01-04        B    8.0  Product1  522.0   East         522.0          8
4  2023-01-05        B   26.0  Product3  869.0  North         869.0         26

In [29]:
df['New Value'] = df['Value'].apply(lambda x:x*2)
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

In [30]:
# data aggregating and grouping

# mean group by product
grouped_mean = df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    48.484848
Product2    59.838710
Product3    43.344828
Name: Value, dtype: float64

In [31]:
# total sales based on product and region
grouped_sum = df.groupby(['Product', 'Region'])['Value'].sum()
grouped_sum

Product   Region
Product1  East      479.0
          North     286.0
          South     329.0
          West      475.0
Product2  East      517.0
          North     359.0
          South     482.0
          West      424.0
Product3  East      250.0
          North     281.0
          South     296.0
          West      430.0
Name: Value, dtype: float64

In [32]:
# aggregate multiple functions
grouped_agg = df.groupby('Region')['Value'].agg(['mean', 'sum', 'count'])
grouped_agg

             mean     sum  count
Region
East    49.840000  1246.0     25
North   44.590909   981.0     22
South   52.045455  1145.0     22
West    54.920000  1373.0     25

In [3]:
# merging and joining dataframes
# create sample dataframe

df1 = pd.DataFrame({'Key': ['A','B','C'], 'Value1': [1,2,3]})
df2 = pd.DataFrame({'Key': ['A','B','D'], 'Value2': [4,5,6]})

In [4]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [5]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [6]:
# merge dataframes on key columns
pd.merge(df1, df2, on="Key", how="inner")

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [ ]:
pd.merge(df1, df2, on="Key", how="outer")

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [8]:
pd.merge(df1, df2, on="Key", how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [9]:
pd.merge(df1, df2, on="Key", how="right")

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6