In [2]:
import pandas as pd
from io import StringIO
Data = '{"employee_name":"James", "email":"james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df = pd.read_json(StringIO(Data))

In [3]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [4]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [5]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [6]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [7]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data", header=None)

In [8]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [9]:
df.to_csv("wine.csv")

In [10]:
!pip install lxml

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lxml in c:\users\asus\appdata\roaming\python\python312\site-packages (6.1.1)

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
!pip

Usage:
  pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  inspect                     Inspect the python environment.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  debug                       Show information useful for debugging.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --debug                     Let unhandled exceptions propagate outside the
                              main subroutine, instead of logging them to
                              stderr.
  --isolated                  Run pip in an isolated mode, ignoring
                              environment variables and user configuration.
  --require-virtualenv        Allow pip to only run in a virtual environment;
                              exit with an error otherwise.
  --python <python>           Run pip with the specified Python interpreter.
  -v, --verbose               Give more output. Option is additive, and can be
                              used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be
                              used up to 3 times (corresponding to WARNING,
                              ERROR, and CRITICAL logging levels).
  --log <path>                Path to a verbose appending log.
  --no-input                  Disable prompting for input.
  --keyring-provider <keyring_provider>
                              Enable the credential lookup via the keyring
                              library if user input is allowed. Specify which
                              mechanism to use [disabled, import, subprocess].
                              (default: disabled)
  --proxy <proxy>             Specify a proxy in the form
                              scheme://[user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should
                              attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists:
                              (s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort.
  --trusted-host <hostname>   Mark this host or host:port pair as trusted,
                              even though it does not have valid or any HTTPS.
  --cert <path>               Path to PEM-encoded CA certificate bundle. If
                              provided, overrides the default. See 'SSL
                              Certificate Verification' in pip documentation
                              for more information.
  --client-cert <path>        Path to SSL client certificate, a single file
                              containing the private key and the certificate
                              in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine
                              whether a new version of pip is available for
                              download. Implied with --no-index.
  --no-color                  Suppress colored output.
  --no-python-version-warning
                              Silence deprecation warnings for upcoming
                              unsupported Pythons.
  --use-feature <feature>     Enable new functionality, that may be backward
                              incompatible.
  --use-deprecated <feature>  Enable deprecated functionality, that will be
                              removed in the future.

In [12]:
url = "https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

df = pd.read_html(url)

In [13]:
df # list of tables

[                                            Bank Name               City  \
 0                                 Small Business Bank             Lenexa
 1       Kentland Federal Savings and Loan Association           Kentland
 2             Community Bank and Trust - West Georgia           LaGrange
 3                   Metropolitan Capital Bank & Trust            Chicago
 4                        The Santa Anna National Bank         Santa Anna
 5                                Pulaski Savings Bank            Chicago
 6                  The First National Bank of Lindsay            Lindsay
 7               Republic First Bank dba Republic Bank       Philadelphia
 8                                       Citizens Bank           Sac City
 9                            Heartland Tri-State Bank            Elkhart
 10                                First Republic Bank      San Francisco
 11                                     Signature Bank           New York
 12                                Silicon Valley Bank        Santa Clara
 13                                  Almena State Bank             Almena
 14                         First City Bank of Florida  Fort Walton Beach
 15                               The First State Bank      Barboursville
 16                                 Ericson State Bank            Ericson
 17                   City National Bank of New Jersey             Newark
 18                                      Resolute Bank             Maumee
 19                              Louisa Community Bank             Louisa
 20                               The Enloe State Bank             Cooper
 21                Washington Federal Bank for Savings            Chicago
 22    The Farmers and Merchants State Bank of Argonia            Argonia
 23                                Fayette County Bank         Saint Elmo
 24  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...          Milwaukee

             State   Cert                     Acquiring Institution  \
 0          Kansas  25744  The Farmers State Bank of Oakley, Kansas
 1         Indiana  28722                             Kentland Bank
 2         Georgia  25796                               Anchor Bank
 3        Illinois  57488                   First Independence Bank
 4           Texas   5520                 Coleman County State Bank
 5        Illinois  28611                           Millennium Bank
 6        Oklahoma   4134                    First Bank & Trust Co.
 7    Pennsylvania  27332         Fulton Bank, National Association
 8            Iowa   8758                 Iowa Trust & Savings Bank
 9          Kansas  25851                    Dream First Bank, N.A.
 10     California  59017                 JPMorgan Chase Bank, N.A.
 11       New York  57053                       Flagstar Bank, N.A.
 12     California  24735       First–Citizens Bank & Trust Company
 13         Kansas  15426                               Equity Bank
 14        Florida  16748                 United Fidelity Bank, fsb
 15  West Virginia  14361                            MVB Bank, Inc.
 16       Nebraska  18265                Farmers and Merchants Bank
 17     New Jersey  21111                           Industrial Bank
 18           Ohio  58317                        Buckeye State Bank
 19       Kentucky  58112         Kentucky Farmers Bank Corporation
 20          Texas  10716                        Legend Bank, N. A.
 21       Illinois  30570                        Royal Savings Bank
 22         Kansas  17719                               Conway Bank
 23       Illinois   1802                 United Fidelity Bank, fsb
 24      Wisconsin  30003       First-Citizens Bank & Trust Company

          Closing Date  Fund  Sort ascending
 0       July 17, 2026                 10553
 1       July 10, 2026                 10552
 2         May 1, 2026                 10551
 3    January 30, 2026                 10550
 4       June 27, 2025                 10549
 5    January 17, 2025                 10548
 6    October 18, 2024                 10547
 7      April 26, 2024                 10546
 8    November 3, 2023                 10545
 9       July 28, 2023                 10544
 10        May 1, 2023                 10543
 11     March 12, 2023                 10540
 12     March 10, 2023                 10539
 13   October 23, 2020                 10538
 14   October 16, 2020                 10537
 15      April 3, 2020                 10536
 16  February 14, 2020                 10535
 17   November 1, 2019                 10534
 18   October 25, 2019                 10533
 19   October 25, 2019                 10532
 20       May 31, 2019                 10531
 21  December 15, 2017                 10530
 22   October 13, 2017                 10529
 23       May 26, 2017                 10528
 24        May 5, 2017                 10527  ]

In [14]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
1,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
2,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
3,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
4,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
5,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
6,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
7,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
8,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
9,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
10,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
11,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
12,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
13,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
14,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
15,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
16,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
17,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
18,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
19,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
20,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
21,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
22,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
23,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
24,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527

In [15]:
url = "https://en.wikipedia.org/wiki/Mobile_country_code"

df = pd.read_html(url, match="Country", header=0) # based on country column of table, iwill patch

HTTPError: HTTP Error 403: Forbidden

In [ ]:
pd.__version__

'3.0.5'

In [ ]:
import requests

url = "https://en.wikipedia.org/wiki/Mobile_country_code"

response = requests.get(url)
print(response.status_code)

403

In [ ]:
!pip install --upgrade beautifulsoup4

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: beautifulsoup4 in c:\users\asus\appdata\roaming\python\python312\site-packages (4.12.2)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\asus\appdata\roaming\python\python312\site-packages (from beautifulsoup4) (2.5)
Collecting typing-extensions>=4.0.0 (from beautifulsoup4)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
   ---------------------------------------- 0.0/109.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/109.9 kB ? eta -:--:--
   --- ------------------------------------ 10.2/109.9 kB ? eta -:--:--
   ---------- ---------------------------- 30.7/109.9 kB 435.7 kB/s eta 0:00:01
   -------------------------------------- 109.9/109.9 kB 712.0 kB/s eta 0:00:00
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
   ---------------------------------------- 0.0/45.6 kB ? eta -:--:--
   ---------------------------------------- 45.6/45.6 kB 1.1 MB/s eta 0:00:00
Installing collected packages: typing-extensions, beautifulsoup4
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.12.2
    Uninstalling beautifulsoup4-4.12.2:
      Successfully uninstalled beautifulsoup4-4.12.2
Successfully installed beautifulsoup4-4.15.0 typing-extensions-4.16.0

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
url = "https://en.wikipedia.org/wiki/Mobile_country_code"
pd.read_html(url, match="Country", header=0)

# 10:14

HTTPError: HTTP Error 403: Forbidden

In [17]:
import requests
from io import StringIO

url = "https://en.wikipedia.org/wiki/Mobile_country_code"
headers = {
    "User-Agent":"Mozilla/5.0"
}
response = requests.get(url, headers=headers, timeout=30)
response.raise_for_status()

tables = pd.read_html(
    StringIO(response.text),
    match="Country",
    header=0
)

tables

[     Mobile country code                                    Country ISO 3166  \
 0                    289                                 A Abkhazia    GE-AB
 1                    412                                Afghanistan       AF
 2                    276                                    Albania       AL
 3                    603                                    Algeria       DZ
 4                    544  American Samoa (United States of America)       AS
 ..                   ...                                        ...      ...
 247                  452                                    Vietnam       VN
 248                  543                        W Wallis and Futuna       WF
 249                  421                                    Y Yemen       YE
 250                  645                                   Z Zambia       ZM
 251                  648                                   Zimbabwe       ZW

                                   Mobile network codes National MNC authority  \
 0             List of mobile network codes in Abkhazia                    NaN
 1          List of mobile network codes in Afghanistan                    NaN
 2              List of mobile network codes in Albania                    NaN
 3              List of mobile network codes in Algeria                    NaN
 4       List of mobile network codes in American Samoa                    NaN
 ..                                                 ...                    ...
 247        List of mobile network codes in the Vietnam                    NaN
 248  List of mobile network codes in Wallis and Futuna                    NaN
 249          List of mobile network codes in the Yemen                    NaN
 250             List of mobile network codes in Zambia                    NaN
 251           List of mobile network codes in Zimbabwe                    NaN

                       Remarks
 0    MCC is not listed by ITU
 1                         NaN
 2                         NaN
 3                         NaN
 4                         NaN
 ..                        ...
 247                       NaN
 248                       NaN
 249                       NaN
 250                       NaN
 251                       NaN

 [252 rows x 6 columns]]

In [18]:
tables[0]

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [4]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/250.9 kB 330.3 kB/s eta 0:00:01
   ----------- --------------------------- 71.7/250.9 kB 563.7 kB/s eta 0:00:01
   -------------------------- ----------- 174.1/250.9 kB 952.6 kB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 1.2 MB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
pd.read_excel('sample_data.xlsx')

    Name  Age
0  Krish   32
1   Jack   34
2   John   31

In [6]:
df_excel = pd.read_excel('sample_data.xlsx')

In [7]:
df_excel.to_pickle('df_excel')

In [8]:
pd.read_pickle('df_excel')

    Name  Age
0  Krish   32
1   Jack   34
2   John   31