# Module: Pandas Assignments
## Lesson: Pandas
### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.
2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.
2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.
2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.
2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.
2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.
2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.
2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.
2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.
2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

In [2]:
# Assignment 1: DataFrame Creation and Indexing

# 1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(1, 25, size=(6,4)), columns=['A','B','C','D'])
print("Original: \n", df)

# set first col to be the index for the rows
modified_df = df.set_index('A')
print("Modified arr: \n", modified_df)

Original:
     A   B   C   D
0   4  18  14  15
1  13  24   3  10
2  19  18  16  19
3  19  16   6  16
4  18  11   2   2
5   7  17  19   5
Modified arr:
      B   C   D
A
4   18  14  15
13  24   3  10
19  18  16  19
19  16   6  16
18  11   2   2
7   17  19   5

In [10]:
# 2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.
# size tells numpy how many random numbers to generate
df = pd.DataFrame(np.random.randint(1, 10, size=(3,3)), index=['X','Y','Z'], columns=['A','B','C'])
print(df)

# accessing element (row = Y, col=B)
print("Element ar row Y, col B: ", df.at['Y','B'])

   A  B  C
X  6  7  2
Y  4  6  9
Z  4  1  2
Element ar row Y, col B:  6

In [9]:
# Assignment 2: DataFrame Operations

# 1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.
df = pd.DataFrame(np.random.randint(1, 16, size=(5,3)))
print("Original: \n", df)

new_col = df[0] * df[1]
print("New columns: \n", new_col)

df['New Col'] = new_col
print("Upated df: \n", df)

Original:
    0   1   2
0  9   3  13
1  7   8  10
2  3   8   1
3  6  14   4
4  9   5   8
New columns:
 0    27
1    56
2    24
3    84
4    45
dtype: int32
Upated df:
    0   1   2  New Col
0  9   3  13       27
1  7   8  10       56
2  3   8   1       24
3  6  14   4       84
4  9   5   8       45

In [14]:
# 2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.
df = pd.DataFrame(np.random.randint(1, 13, size=(4,3)))
print("Original: \n", df)

row_wise_sum = df.sum(axis=1)
print("Row wise sum: \n", row_wise_sum)

col_wise_sum = df.sum(axis=0)
print("Col wise sum: \n", col_wise_sum)

Original:
     0   1   2
0   1  12  12
1   8  11   8
2  12   8   5
3  11   6   2
Row wise sum:
 0    25
1    27
2    25
3    19
dtype: int64
Col wise sum:
 0    32
1    37
2    27
dtype: int64

In [21]:
# Assignment 3: Data Cleaning

# 1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.
df = pd.DataFrame(np.random.randint(1, 16, size=(5,3)))
print("Original: \n", df)

# some nan values
df.iloc[0, 1] = np.nan
df.iloc[2, 2] = np.nan
df.iloc[4, 0] = np.nan
print("Filled with some nan values: \n", df)

mean = df.mean(skipna=True)
print("Mean of df column's: \n", mean)

df.fillna(mean, inplace=True)

Original:
     0   1   2
0  12  14   1
1   9  10  12
2   9  13  11
3   9  12   9
4   9   4  15
Filled with some nan values:
       0     1     2
0  12.0   NaN   1.0
1   9.0  10.0  12.0
2   9.0  13.0   NaN
3   9.0  12.0   9.0
4   NaN   4.0  15.0
Mean of df column's:
 0    9.75
1    9.75
2    9.25
dtype: float64

       0      1      2
0  12.00   9.75   1.00
1   9.00  10.00  12.00
2   9.00  13.00   9.25
3   9.00  12.00   9.00
4   9.75   4.00  15.00

In [29]:
# 2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.
df = pd.DataFrame(np.random.randint(1, 25, size=(6,4)))
print("Original: \n", df)

# some nan values
df.iloc[0, 1] = np.nan
df.iloc[2, 2] = np.nan
df.iloc[4, 0] = np.nan
print("Filled with some nan values: \n", df)

df.dropna(axis=0, inplace=True)
print("Dropped rows with nan values: \n", df)

Original:
     0   1   2   3
0  17  14  12   4
1   5   1  15   1
2  12  15  12   3
3  18   3  21  11
4  11  24   1  10
5   2  12  14  21
Filled with some nan values:
       0     1     2   3
0  17.0   NaN  12.0   4
1   5.0   1.0  15.0   1
2  12.0  15.0   NaN   3
3  18.0   3.0  21.0  11
4   NaN  24.0   1.0  10
5   2.0  12.0  14.0  21
Dropped rows with nan values:
       0     1     2   3
1   5.0   1.0  15.0   1
3  18.0   3.0  21.0  11
5   2.0  12.0  14.0  21

In [45]:
# Assignment 4: Data Aggregation

# 1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.
df = pd.DataFrame({'Category': np.random.choice(['A','B','C'], size=10), 'Value': np.random.randint(20, 100, size=10)})
print("Df: \n", df)

# sum and mean of each category
# only consider value column
sum_mean = df.groupby(by='Category')['Value'].agg(['sum', 'mean'])
print("Sum and mean of each category: \n", sum_mean)

Df:
   Category  Value
0        C     83
1        C     42
2        B     51
3        A     54
4        B     67
5        B     49
6        A     65
7        A     58
8        A     48
9        B     51
Sum and mean of each category:
           sum   mean
Category
A         225  56.25
B         218  54.50
C         125  62.50

In [47]:
# 2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.
df = pd.DataFrame({'Product': np.random.choice(['P1','P2','P3'], size=10), 'Category': np.random.choice(['C1','C2','C3'], size=10), 'Sales': np.random.randint(20, 100, size=10)})
print("Original dataframe: \n", df)

total_sales = df.groupby(by='Category')['Sales'].sum()
print("Total sales for each category: \n", total_sales)

Original dataframe:
   Product Category  Sales
0      P3       C1     58
1      P3       C1     45
2      P1       C2     94
3      P3       C2     84
4      P1       C3     35
5      P3       C2     76
6      P3       C1     53
7      P3       C1     31
8      P3       C2     93
9      P2       C2     56
Total sales for each category:
 Category
C1    187
C2    403
C3     35
Name: Sales, dtype: int32

In [ ]:
# Assignment 5: Merging DataFrames

# 1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.
df1 = pd.DataFrame({'Key': ['A','B','C','D'], 'Value1': np.random.randint(1, 100, size=4)})
df2 = pd.DataFrame({'Key': ['A','B','M','E'], 'Value2': np.random.randint(1, 100, size=4)})

print("Original df1: \n", df1)
print("\nOriginal df2: \n", df2)

# merging dataframes
df3 = pd.merge(df1, df2,on='Key', how='outer')
df3

Original df1:
   Key  Value1
0   A      27
1   B      43
2   C       1
3   D      89

Original df2:
   Key  Value2
0   A      77
1   B      35
2   M      23
3   E       9

  Key  Value1  Value2
0   A    27.0    77.0
1   B    43.0    35.0
2   C     1.0     NaN
3   D    89.0     NaN
4   E     NaN     9.0
5   M     NaN    23.0

In [ ]:
# 2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.
df1 = pd.DataFrame({'A': np.random.randint(1, 100, size=3), 'B': np.random.randint(1, 100, size=3)})
df2 = pd.DataFrame({'C': np.random.randint(1, 100, size=3), 'D': np.random.randint(1, 100, size=3)})


print("Original df1: \n", df1)
print("\nOriginal df2: \n", df2)


# pd.concat() never joins data by position alone. It aligns using labels:

# axis=0 (row-wise): aligns by column names. If one DataFrame is missing a column, Pandas fills those cells with NaN.
# axis=1 (column-wise): aligns by row indexes. If one DataFrame is missing an index, Pandas fills those cells with NaN.
df3 = pd.concat([df1, df2], axis=0)
print("\nConcat along rows: \n", df3)

df4 = pd.concat([df1, df2], axis=1)
print("\nConcat along cols: \n", df4)

Original df1:
     A   B
0  36  28
1  87  18
2  24  87

Original df2:
     C   D
0  98   6
1  17  67
2   2  69

Concat along rows:
       A     B     C     D
0  36.0  28.0   NaN   NaN
1  87.0  18.0   NaN   NaN
2  24.0  87.0   NaN   NaN
0   NaN   NaN  98.0   6.0
1   NaN   NaN  17.0  67.0
2   NaN   NaN   2.0  69.0

Concat along cols:
     A   B   C   D
0  36  28  98   6
1  87  18  17  67
2  24  87   2  69

In [14]:
# Assignment 6: Time Series Analysis

# 1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resampledf  the DataFrame to compute the monthly mean of the values.
dates = pd.date_range(start='2026-01-01', end='2026-12-31', freq='D')
print("Dates: \n", dates)

df = pd.DataFrame({'Date': dates, 'Data': np.random.randint(1, 100, size=(len(dates)))})
df.set_index(keys='Date', inplace=True)
print("\nDf: \n", df)

# monthly mean of values
monthly_mean = df.resample('ME').mean()
print("\n Monthly mean: \n", monthly_mean)

Dates:
 DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10',
               ...
               '2026-12-22', '2026-12-23', '2026-12-24', '2026-12-25',
               '2026-12-26', '2026-12-27', '2026-12-28', '2026-12-29',
               '2026-12-30', '2026-12-31'],
              dtype='datetime64[us]', length=365, freq='D')

Df:
             Data
Date
2026-01-01    74
2026-01-02    70
2026-01-03    34
2026-01-04    66
2026-01-05    43
...          ...
2026-12-27     1
2026-12-28    56
2026-12-29    71
2026-12-30     3
2026-12-31    41

[365 rows x 1 columns]

 Monthly mean:
                  Data
Date
2026-01-31  53.483871
2026-02-28  58.642857
2026-03-31  53.064516
2026-04-30  54.433333
2026-05-31  53.806452
2026-06-30  50.700000
2026-07-31  40.870968
2026-08-31  53.580645
2026-09-30  52.266667
2026-10-31  50.645161
2026-11-30  37.866667
2026-12-31  48.935484

In [19]:
# 2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.
dates = pd.date_range(start='2026-01-01', end='2026-12-31', freq='D')
print("Dates: \n", dates)

df = pd.DataFrame({'Date': dates, 'Data': np.random.randint(1, 100, size=(len(dates)))})
df.set_index('Date', inplace=True)
print("\nDf: \n", df)

# rolling mean with window of 7 days
rolling_mean = df.rolling(window=7).mean()
print("\nRolling mean with a window of 7 days: \n", rolling_mean)

Dates:
 DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10',
               ...
               '2026-12-22', '2026-12-23', '2026-12-24', '2026-12-25',
               '2026-12-26', '2026-12-27', '2026-12-28', '2026-12-29',
               '2026-12-30', '2026-12-31'],
              dtype='datetime64[us]', length=365, freq='D')

Df:
             Data
Date
2026-01-01    16
2026-01-02    54
2026-01-03    97
2026-01-04    27
2026-01-05     8
...          ...
2026-12-27    34
2026-12-28    78
2026-12-29    79
2026-12-30    68
2026-12-31    45

[365 rows x 1 columns]

Rolling mean with a window of 7 days:
                  Data
Date
2026-01-01        NaN
2026-01-02        NaN
2026-01-03        NaN
2026-01-04        NaN
2026-01-05        NaN
...               ...
2026-12-27  41.857143
2026-12-28  47.714286
2026-12-29  54.000000
2026-12-30  60.571429
2026-12-31  62.571429

[365 rows x 1 columns]

In [ ]:
# Assignment 7: MultiIndex DataFrame

# 1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.
arrays = [['A','A','B','B'], ['one', 'two', 'one', 'two']]
print("Arrays: \n", arrays)

index = pd.MultiIndex.from_arrays(arrays=arrays, names=('Category', 'Subcategory'))
print("\nIndex: \n", index)

df = pd.DataFrame(np.random.randint(1, 100, size=(4,3)), index=index, columns=['Value1', 'Value2', 'Value3'])
print("\nDf: \n", df)

print("\nParent index A: \n", df.loc['A'])

print("\nOne particular row: \n", df.loc[('B', 'two')])

Arrays:
 [['A', 'A', 'B', 'B'], ['one', 'two', 'one', 'two']]

Index:
 MultiIndex([('A', 'one'),
            ('A', 'two'),
            ('B', 'one'),
            ('B', 'two')],
           names=['Category', 'Subcategory'])

Df:
                       Value1  Value2  Value3
Category Subcategory
A        one              88      90      70
         two              85       3      14
B        one              87      94      15
         two              98      17      89

Parent index A:
              Value1  Value2  Value3
Subcategory
one              88      90      70
two              85       3      14

One particular row:
 Value1    98
Value2    17
Value3    89
Name: (B, two), dtype: int32

In [7]:
# 2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.
arrays = [['A','A','B','B','C','C'], ['one', 'two', 'one', 'two', 'one', 'two']]
print("Arrays: \n", arrays)

index = pd.MultiIndex.from_arrays(arrays=arrays, names=('Category', 'Subcategory'))

df = pd.DataFrame(np.random.randint(1, 100, size=(6, 3)), index=index, columns=['V1', 'V2', 'V3'])
print("\n Df: \n", df)

# sum of values for each category and subcategory
df['Total'] = df.sum(axis=1)
print("\nCategory and subcategory wise sum: \n", df)

Arrays:
 [['A', 'A', 'B', 'B', 'C', 'C'], ['one', 'two', 'one', 'two', 'one', 'two']]

 Df:
                       V1  V2  V3
Category Subcategory
A        one          71  73  77
         two          46  45  26
B        one          69  28   9
         two          21  85  65
C        one          34  25  16
         two          26  95  75

Category and subcategory wise sum:
                       V1  V2  V3  Total
Category Subcategory
A        one          71  73  77    221
         two          46  45  26    117
B        one          69  28   9    106
         two          21  85  65    171
C        one          34  25  16     75
         two          26  95  75    196

In [ ]:
# Assignment 8: Pivot Tables

# 1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.
date_range = pd.date_range(start='2026-08-17', end='2026-08-27', freq='D')
print("Date ranges: \n", date_range)

df = pd.DataFrame({'Date': np.random.choice(date_range, size=20), 'Category': np.random.choice(['A', 'B', 'C'], size=20), 'Value': np.random.randint(1, 100, size=20)})
print("\nOriginal dataframe: \n", df)

# making a pivot table
pivot = df.pivot_table(values='Value', index='Date', columns='Category', aggfunc='sum')
print("\nPrinting pivot table: \n", pivot)

Date ranges:
 DatetimeIndex(['2026-08-17', '2026-08-18', '2026-08-19', '2026-08-20',
               '2026-08-21', '2026-08-22', '2026-08-23', '2026-08-24',
               '2026-08-25', '2026-08-26', '2026-08-27'],
              dtype='datetime64[us]', freq='D')

Original dataframe:
          Date Category  Value
0  2026-08-17        B     34
1  2026-08-23        C     86
2  2026-08-22        A     88
3  2026-08-24        B     83
4  2026-08-18        A      7
5  2026-08-24        C     65
6  2026-08-26        A     10
7  2026-08-22        B     98
8  2026-08-24        A     20
9  2026-08-25        C     48
10 2026-08-27        C     18
11 2026-08-22        C     68
12 2026-08-25        A     21
13 2026-08-17        C     28
14 2026-08-22        A     99
15 2026-08-22        C      3
16 2026-08-17        B     22
17 2026-08-26        B     29
18 2026-08-17        C      5
19 2026-08-22        A     17

Printing pivot table:
 Category        A     B     C
Date
2026-08-17    NaN  56.0  33.0
2026-08-18    7.0   NaN   NaN
2026-08-22  204.0  98.0  71.0
2026-08-23    NaN   NaN  86.0
2026-08-24   20.0  83.0  65.0
2026-08-25   21.0   NaN  48.0
2026-08-26   10.0  29.0   NaN
2026-08-27    NaN   NaN  18.0

In [ ]:
# 2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.
df = pd.DataFrame({'Year': np.random.choice([2024, 2025, 2026], size=12), 'Quarter': np.random.choice(['Q1', 'Q2', 'Q3', 'Q4'], size=12), 'Revenue': np.random.randint(1, 100, size=12)})
print("Original dataframa: \n", df)

# pivot table
pivot = df.pivot_table(values='Revenue', index='Year', columns='Quarter', aggfunc='mean')
print("\nMean revenue for each quarter by year: \n", pivot)

Original dataframa:
     Year Quarter  Revenue
0   2026      Q4       52
1   2026      Q1       45
2   2026      Q2       56
3   2025      Q2       95
4   2025      Q4       24
5   2025      Q3       47
6   2024      Q2       64
7   2025      Q1       56
8   2026      Q3       53
9   2026      Q4       65
10  2026      Q4       58
11  2025      Q1       77

 Mean revenue for each quarter by year:
 Quarter    Q1    Q2    Q3         Q4
Year
2024      NaN  64.0   NaN        NaN
2025     66.5  95.0  47.0  24.000000
2026     45.0  56.0  53.0  58.333333

In [35]:
# Assignment 9: Applying Functions

# 1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.
df = pd.DataFrame(np.random.randint(1, 100, size=(5,3)), columns=['A','B','C'])
print(type(df))
print("Original dataframe: \n", df)

import pandas as pd
print(pd.__version__)
print(hasattr(pd.DataFrame, "applymap"))
print(hasattr(df, "applymap"))
print(df.__class__)

# applymap applies the lambda fuction on each cell of dataframe
doubled_df = df.applymap(lambda x : x*2)
print("\nDoubed value: \n", doubled_df)

<class 'pandas.DataFrame'>
Original dataframe:
     A   B   C
0  74  81  49
1   4  86  93
2  53  97  23
3  96  66  78
4  13  68  19
3.0.5
False
False
<class 'pandas.DataFrame'>

AttributeError: 'DataFrame' object has no attribute 'applymap'

In [ ]:
!pip install --upgrade pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata in C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [31]:
!python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in c:\program files\python312\lib\site-packages (24.0)
Collecting pip
  Downloading pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)
Downloading pip-26.2.1-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   - -------------------------------------- 0.1/1.8 MB 1.1 MB/s eta 0:00:02
   ----- ---------------------------------- 0.2/1.8 MB 2.4 MB/s eta 0:00:01
   ------ --------------------------------- 0.3/1.8 MB 2.0 MB/s eta 0:00:01
   --------- ------------------------------ 0.4/1.8 MB 2.3 MB/s eta 0:00:01
   ---------- ----------------------------- 0.5/1.8 MB 2.0 MB/s eta 0:00:01
   ------------- -------------------------- 0.6/1.8 MB 2.2 MB/s eta 0:00:01
   ----------------- ---------------------- 0.8/1.8 MB 2.5 MB/s eta 0:00:01
   ------------------ --------------------- 0.9/1.8 MB 2.4 MB/s eta 0:00:01
   ---------------------- ----------------- 1.0/1.8 MB 2.5 MB/s eta 0:00:01
   --------------------------- ------------ 1.2/1.8 MB 2.6 MB/s eta 0:00:01
   ------------------------------ --------- 1.4/1.8 MB 2.8 MB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.8 MB 2.9 MB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.8 MB 2.7 MB/s eta 0:00:01
   ------------------------------------- -- 1.7/1.8 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 2.6 MB/s eta 0:00:00
Installing collected packages: pip
Successfully installed pip-26.2.1

In [36]:
import sys
import pandas as pd

print("Python:", sys.executable)
print("Pandas file:", pd.__file__)
print("Version:", pd.__version__)
print("Has applymap:", hasattr(pd.DataFrame, "applymap"))

Python: c:\Program Files\Python312\python.exe
Pandas file: C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py
Version: 3.0.5
Has applymap: False

In [37]:
%pip install --upgrade pandas

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pandas in C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata in C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [1]:
import pandas as pd
print(pd.__version__)
print(hasattr(pd.DataFrame, "applymap"))

3.0.5
False

In [7]:
# Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.
df = pd.DataFrame(np.random.randint(1, 100, size=(6,3)), columns=['A','B','C']) 
print("Original dataframe: \n", df)

df['total'] = df.apply(lambda row: row.sum(), axis=1)
print("\nUpdated dataframe: \n", df)

Original dataframe:
     A   B   C
0  56  22  94
1  54  59  36
2  20  65  88
3  95  59   5
4  73  30  34
5  83   1  42

Updated dataframe:
     A   B   C  total
0  56  22  94    172
1  54  59  36    149
2  20  65  88    173
3  95  59   5    159
4  73  30  34    137
5  83   1  42    126

In [ ]:
# Assignment 10: Working with Text Data

# 1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.
text_data = pd.Series(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print("Text data: \n", text_data)

text_data = text_data.str.upper()
print("\nUppercase strings: \n", text_data)

Text data:
 0         apple
1        banana
2        cherry
3          date
4    elderberry
dtype: str

Uppercase strings:
 0         APPLE
1        BANANA
2        CHERRY
3          DATE
4    ELDERBERRY
dtype: str

In [13]:
# 2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.
text_data = pd.Series(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print("Text data: \n", text_data)

first_chars = text_data.str[:3]
print("\nFirst 3 characters of each string: \n", first_chars)

Text data:
 0         apple
1        banana
2        cherry
3          date
4    elderberry
dtype: str

First 3 characters of each string:
 0    app
1    ban
2    che
3    dat
4    eld
dtype: str